modLoader = "javafml"
loaderVersion = "${forgeLoaderVersion}"
license = "MIT"
showAsResourcePack = false
properties = {}
issueTrackerURL = "${issues}"
[[mods]]
modId = "pl3xmap"
version = "${version}"
displayName = "${name}"
description = "${description}"
logoFile = "pl3xmap.png"
logoBlur = false
#updateJSONURL = ""
modproperties = {}
#credits = ""
authors = ${authors}
displayURL = "${website}"
displayTest = "IGNORE_SERVER_VERSION"
[[dependencies.pl3xmap]]
modId = "forge"
mandatory = true
versionRange = "${forgeLoaderVersion}"
ordering = "AFTER"
side = "SERVER"
[[dependencies.pl3xmap]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "AFTER"
side = "SERVER"
