modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
issueTrackerURL = "https://github.com/BillyGalbreath/Pl3xMap/issues"
[[mods]]
modId = "pl3xmap"
version = "${version}"
displayName = "Pl3xMap"
displayURL = "https://modrinth.com/plugin/pl3xmap"
logoFile = "pl3xmap.png"
#credits = ""
authors = "BillyGalbreath"
displayTest = "IGNORE_SERVER_VERSION"
description = "Minimalistic and lightweight world map viewer for Minecraft servers"
