# This is the main configuration file for Pl3xMap
#
# If you need help with the configuration or have any
# questions related to Pl3xMap, join us in our Discord
#
# Discord: https://discord.gg/nhGzEkwXQX
# Wiki: https://github.com/pl3xgaming/Pl3xMap/wiki

settings:
  debug-mode: false
  language-file: "lang-en.yml"
  web-directory:
    path: "web"
    read-only: false
  internal-webserver:
    enabled: true
    bind: "0.0.0.0"
    port: 8080
