name: "${name}"
main: "${group}.${name}"
version: "${version}"
api-version: "1.18"
author: "BillyGalbreath"
description: "${description}"

permissions:
  pl3xmap.command.map:
    default: op

  pl3xmap.command.fullrender:
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.help:
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.hide:
    default: op
    children:
      pl3xmap.command.map: true
  pl3xmap.command.hide.others:
    default: op
    children:
      pl3xmap.command.hide: true

  pl3xmap.command.reload:
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.show:
    default: op
    children:
      pl3xmap.command.map: true
  pl3xmap.command.show.others:
    default: op
    children:
      pl3xmap.command.show: true

  pl3xmap.command.status:
    default: op
    children:
      pl3xmap.command.map: true
