name: "Pl3xMap"
main: "net.pl3x.map.bukkit.Pl3xMapBukkit"
version: "${version}"
api-version: "1.18"
author: "BillyGalbreath"
description: "Minimalistic and lightweight world map viewer for Minecraft servers"
website: "https://modrinth.com/plugin/pl3xmap"
