settings:
  debug-mode: false
world-settings:
  default:
    enabled: false
  world:
    enabled: true
    ui:
      display-name: Overworld
      order: 0
  world_nether:
    render:
      skylight: 10
    ui:
      display-name: The Nether
      order: 1
  world_the_end:
    render:
      skylight: 10
    ui:
      display-name: The End
      order: 2
