settings:
  debug-mode: false
world-settings:
  default:
    enabled: true
    render:
      renderers:
        vintage_story: overworld_basic
      skylight: 15
  world:
    enabled: true
    render:
      renderers:
        vintage_story: overworld_basic
    ui:
      display-name: Overworld
      order: 0
  world_nether:
    render:
      renderers:
        basic: nether_basic
      skylight: 0
    ui:
      display-name: The Nether
      order: 1
  world_the_end:
    render:
      renderers:
        basic: the_end_basic
      skylight: 0
    ui:
      display-name: The End
      order: 2
