settings:
  debug-mode: false
world-settings:
  default:
    enabled: true
    render:
      renderers:
        basic: overworld_basic
        night: overworld_night
        biomes: overworld_biomes
        inhabited: inhabited
      skylight: 15
  world:
    enabled: true
    render:
      renderers:
        basic: overworld_basic
        night: overworld_night
        biomes: overworld_biomes
        inhabited: inhabited
        flowermap: flowermap
    ui:
      display-name: Overworld
      order: 0
  world_nether:
    render:
      renderers:
        basic: nether_basic
        night: nether_night
        biomes: nether_biomes
        inhabited: inhabited
      skylight: 0
    ui:
      display-name: The Nether
      order: 1
  world_the_end:
    render:
      renderers:
        basic: the_end_basic
        night: the_end_night
        biomes: the_end_biomes
        inhabited: inhabited
      skylight: 0
    ui:
      display-name: The End
      order: 2
