name: Build
on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install npm dependencies
        run: cd webmap && npm ci --ignore-scripts && cd ../
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Pl3xMap-v2
          path: |
            build/libs
            !build/libs/*-dev*
      - name: Generate Javadoc
        run: ./gradlew javadoc
      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: javadoc
          clean: true
          folder: plugin/build/docs/javadoc
          target-folder: ./
