name: Build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm modules
        run: npm install
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Pl3xMap-v2
          path: |
            build/libs
            !build/libs/*-dev*
