name: Build
on:
  push:
    branches:
      - v3

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Import gradle properties
        shell: bash
        run: cat gradle.properties >> $GITHUB_ENV
      - name: Shut ForgeGradle Up
        run: ./gradlew hideOfficialWarningUntilChanged
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Generate Javadoc
        run: ./gradlew javadoc
      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: javadoc
          clean: true
          folder: core/build/docs/javadoc
          target-folder: ./
      #- name: Publish to Hangar
      #  run: ./gradlew publishPluginPublicationToHangar --stacktrace
      #  env:
      #    HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
      #    COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '<br>') }}
      - name: Publish to Modrinth
        run: ./gradlew modrinth_nobuild --stacktrace
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '<br>') }}
        continue-on-error: true
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: New build of Pl3xMap is ready!
          description: |
            Version ${{ env.minecraftVersion }} build ${{ github.run_number }}
            Click [here](https://modrinth.com/mod/pl3xmap/version/${{ env.minecraftVersion }}-${{ github.run_number }}) to download!
