name: Build
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm modules
        run: cd webmap && npm install && cd ../
      - name: Build
        run: ./gradlew build --stacktrace
