name: "${name}"
main: "${group}.Paper${name}"
version: "${version}"
api-version: "1.19"
author: "BillyGalbreath"
description: "${description}"

permissions:
  pl3xmap.command.map:
    description: Gives access to the base command
    default: op

  pl3xmap.command.addons:
    description: Gives access to list addons
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.addons.load:
    description: Gives access to load addons
    default: op
    children:
      pl3xmap.command.addons: true

  pl3xmap.command.addons.unload:
    description: Gives access to unload addons
    default: op
    children:
      pl3xmap.command.addons: true

  pl3xmap.command.cancelrender:
    description: Gives access to cancel renders
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.confirm:
    description: Gives access to confirm dangerous commands
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.fullrender:
    description: Gives access to start full renders
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.help:
    description: Gives access to view the help menu
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.hide:
    description: Gives access to hide self on the map
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.hide.others:
    description: Gives access to hide others on the map
    default: op
    children:
      pl3xmap.command.hide: true

  pl3xmap.command.pauserender:
    description: Gives access to pause and unpause renders
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.radiusrender:
    description: Gives access to start radius renders
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.reload:
    description: Gives access to reload the plugin amd configs
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.resetmap:
    description: Gives access to reset entire maps
    default: op
    children:
      pl3xmap.command.map: true
      pl3xmap.command.confirm: true

  pl3xmap.command.show:
    description: Gives access to show self on the map
    default: op
    children:
      pl3xmap.command.map: true

  pl3xmap.command.show.others:
    description: Gives access to show others on the map
    default: op
    children:
      pl3xmap.command.show: true

  pl3xmap.command.status:
    description: Gives access to view render status
    default: op
    children:
      pl3xmap.command.map: true
